AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'v1.0

  Sample SAM Template for v1.0

  '
Globals:
  Function:
    Timeout: 120
Resources:
  SixechoApi100:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://database-s3-y1kxwr2ft5fq/swagger.yml
  DigestCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://database-s3-y1kxwr2ft5fq/72105241ceaf4943f05fbfef9af5d992
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
      - AmazonVPCFullAccess
      - Statement:
        - Effect: Allow
          Action:
          - ssm:GetParameter
          - ssm:GetParameters
          Resource: '*'
      - Statement:
        - Effect: Allow
          Action: lambda:InvokeFunction
          Resource:
            Fn::ImportValue: FN::ContractClient
      Environment:
        Variables:
          REDIS_URL: redis://sixr-leaderboard.rezkjn.ng.0001.apse1.cache.amazonaws.com:6379
          CONTRACT_CLIENT_FUNCTION:
            Fn::ImportValue: FN::ContractClient
      VpcConfig:
        SecurityGroupIds:
        - sg-0f8be61e92ce25fa2
        SubnetIds:
        - subnet-0eae485b84ba86984
        - subnet-0f81bee03aeafa36e
        - subnet-0ad3d7569bc683087
        - subnet-0fa7a627c045e0519
        - subnet-004048eaf89b38053
      Events:
        DigestChecker:
          Type: Api
          Properties:
            Path: /wallet/balance
            Method: ANY
            RestApiId:
              Ref: SixechoApi100
  ApiGatewayInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - DigestCheckerFunction
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ':'
          - Ref: AWS::AccountId
          - ':'
          - Ref: DigestCheckerFunction
          - /*/*/*
Outputs:
  DigestCheckerFunction:
    Description: Digest Checker Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DigestCheckerFunction
      - Arn
