AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  v1.0

  Sample SAM Template for v1.0

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120 

Resources:
  SixechoApi100:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
          Fn::Transform:
            Name: 'AWS::Include'
            Parameters:
              Location: s3://database-s3-y1kxwr2ft5fq/swagger.yml
  DigestCheckerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: digest_checker/
      Handler: app.lambda_handler
      Runtime: python2.7
      Policies:
        - AmazonVPCFullAccess
        - Statement:
          -
            Effect: "Allow"
            Action:
              - "ssm:GetParameter"
              - "ssm:GetParameters"
            Resource: "*"             
        - Statement:
            - 
              Effect: Allow
              Action: "lambda:InvokeFunction"
              Resource: !ImportValue "FN::ContractClient"     
      Environment:
        Variables:
          REDIS_URL: redis://sixr-leaderboard.rezkjn.ng.0001.apse1.cache.amazonaws.com:6379
          CONTRACT_CLIENT_FUNCTION: !ImportValue "FN::ContractClient"
      VpcConfig:
        SecurityGroupIds:
          - sg-0f8be61e92ce25fa2
        SubnetIds:
          - subnet-0eae485b84ba86984
          - subnet-0f81bee03aeafa36e
          - subnet-0ad3d7569bc683087
          - subnet-0fa7a627c045e0519
          - subnet-004048eaf89b38053
      Events:
        DigestChecker:
          Type: Api 
          Properties:
            Path: /wallet/balance
            Method: ANY
            RestApiId: !Ref SixechoApi100 

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DigestCheckerFunction:
    Description: "Digest Checker Lambda Function ARN"
    Value: !GetAtt DigestCheckerFunction.Arn

  
