AWSTemplateFormatVersion: '2010-09-09'
Description: 'wallet

  Sample SAM Template for wallet

  '
Globals:
  Function:
    Timeout: 45
Outputs:
  ContractClient:
    Description: ContractClient Lambda Function ARN
    Export:
      Name: FN::ContractClient
    Value:
      Fn::GetAtt:
      - ContractClient
      - Arn
Resources:
  ContractClient:
    Properties:
      CodeUri: s3://database-s3-y1kxwr2ft5fq/f7791db9034601ea1c955008aef6b80a
      Environment:
        Variables:
          API_CONTRACT_ADDRESS: '0x7ba0dc44234a90b8e15eadb094c79dc5352b83a3'
          NETWORK_PROVIDER_URL: https://api.baobab.klaytn.net:8651
      Handler: index.handler
      Policies:
      - Statement:
        - Action:
          - ssm:GetParameter
          - ssm:GetParameters
          Effect: Allow
          Resource: '*'
      Runtime: nodejs10.x
      Timeout: 45
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
