AWSTemplateFormatVersion: '2010-09-09'
Description: 'wallet

  Sample SAM Template for wallet

  '
Globals:
  Function:
    Timeout: 60
Outputs:
  ContractClient:
    Description: ContractClient Lambda Function ARN
    Export:
      Name: FN::ContractClient
    Value:
      Fn::GetAtt:
      - ContractClient
      - Arn
Resources:
  ContractClient:
    Properties:
      CodeUri: s3://database-s3-y1kxwr2ft5fq/2803f10674765354fcca8bc5ae65baf1
      Environment:
        Variables:
          API_CONTRACT_ADDRESS: 109868394583226093725357810955894381932170045939
          NETWORK_PROVIDER_URL: https://api.baobab.klaytn.net:8651
      Handler: index.handler
      Policies:
      - Statement:
        - Action:
          - ssm:GetParameter
          - ssm:GetParameters
          Effect: Allow
          Resource: '*'
      Runtime: nodejs10.x
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
