AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  wallet

  Sample SAM Template for wallet

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 45

Resources:
  ContractClient:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: contract_client/
      Handler: index.handler
      Runtime: nodejs10.x
      Timeout: 45
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          API_CONTRACT_ADDRESS: "0xefb251d55d3ddf9e5cb05a52a1e47233e7ce1f83"
          NETWORK_PROVIDER_URL:
            https://api.baobab.klaytn.net:8651
      Policies:
        - Statement:
            - Effect: "Allow"
              Action:
                - "ssm:GetParameter"
                - "ssm:GetParameters"
                - "kms:Decrypt"
              Resource: "*"
              
  GenerateWallet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generate_wallet/
      Handler: index.handler
      Runtime: nodejs10.x
      Timeout: 45
      Environment:
        Variables:
          NETWORK_PROVIDER_URL: https://api.baobab.klaytn.net:8651

# Outputs:
  # ContractClient:
  #   Description: "ContractClient Lambda Function ARN"
  #   Value: !GetAtt ContractClient.Arn
  #   Export:
  #     Name: FN::ContractClient
